#:kivy 2.3.1

<MainWidget>: # Regra do kivy
    orientation: 'vertical' # Divide a tela em 2 caixas horizontais
    canvas: 
        Color: 
            rgb: 0.5,0.5,0.5 # Cinza
        Rectangle: # Desenha uma caixa retangular
            size: self.size
    BoxLayout:
        orientation: 'horizontal' # Cria um layout filho que vai ser divido em duas caixas veticais
        size_hint: (1,0.12)
        spacing: 10 
        Label:
            text: 'SCADA Refrigeração v1.0'
            size_hint_x: None
            width: 300
        BoxLayout:
            orientation:'vertical' # Vai "empilhar" coisas uma em cima da outra
            size_hint_x: None # Desabilita o dimensionamento horizontal
            width: 400
            Label:
                text: 'Configurações de conexão'
            BoxLayout:
                orientation:'horizontal'
                Button: 
                    text: "MODBUS"
                    on_release: root._modbusPopup.open()
                Button: 
                    text: "Scan Time"
                    on_release: root._scanPopup.open()
        Image:
            id: img_con
            size_hint_x: None
            width: 80
            source: 'assets/desconectado.png'
            pos_hint: {'top':1,'right':1}
### DAQUI PRA CIMA FOI FEITA A BARRA DE CIMA DO LAYOUT ###

### DAQUI PRA BAIXO FOI FEITA A BARRA DE BAIXO ###

    FloatLayout:
        canvas:
            Color:
                rgb: 1,1,1 # Fundo branco para não ter contraste em relação a imagem de fundo
            Rectangle: 
                size: self.size
        Image: 
            source: 'assets/fundo.png'


        
        Label:
            id:  encoder_axial #Rotação mecânica do ventilador
            text: '-.- RPM'
            fint_size: 25
            bold: True
            halign: 'center'
            pos_hint: {'x':-0.280,'y':0.460}
            color: 0.4,0.4,0.4,1

        TempLabel:
            id:  torque_axial
            text: '-.- N.m'
            pos_hint: {'x':-0.420,'y':0.35}

        TempLabel:
            id:  pit01 #Pressão do tubo azul 
            text: '-.- psi'
            pos_hint: {'x':-0.030,'y':0.06}


        TempLabel:
            id:  pit02 #Pressão do tubo vermelho
            text: '-.- psi'
            pos_hint: {'x':0.02,'y':-0.09}

        TempLabel:
            id:  pit03 #Pressão do ar de entrada
            text: '-.- mmH2O'
            pos_hint: {'x':0.05,'y':0.460}

        TempLabel:
            id: tit01 #Temperatura do tubo azul
            text: '-.- °C'
            pos_hint: {'x':-0.045,'y':0.125}

        TempLabel:
            id: tit02 #Temperatura do tubo vermelho (trocador de calor)
            text: '-.- °C'
            pos_hint: {'x':-0.015,'y':-0.340}

        TempLabel:
            id: vazao #Vazão do ar na saída do tubo
            text: '-.- m³/h'
            pos_hint: {'x':0.34,'y':0.25}

        TempLabel:
            id: velocidade #Velocidade do ar na saída do tubo
            text: '-.- m/s'
            pos_hint: {'x':0.34,'y':0.10}

        TempLabel:
            id: temperatura #temperatura do ar na saída do tubo
            text: '-.- °C'
            pos_hint: {'x':0.34,'y':-0.05}


        #ACIONAMENTO DO COMPRESSOR 1 (DECIDIR QUAL)
        Button: 
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (145,12)
            background_normal: 'assets/acionamento.png'
            background_down: 'assets/acionamento.png'
            on_release:
                root._co_compressor.open() #CRIAR UM LAYOUT PARA ABRIR QUANDO Clicar no acionamento do compressor
        Button: #Gráfico do compressor 1 (DECIDIR QUAL)
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (185,12)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() #CRIAR UM GRÁFICO PARA ABRIR AO CLICAR


        #ACIONAMENTO O MOTOR
        Button: 
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (123,361)
            background_normal: 'assets/acionamento.png'
            background_down: 'assets/acionamento.png'
            on_release:
                root._co_motor.open() #CRIAR UM LAYOUT PARA ABRIR QUANDO CLICAR
        Button: #Gráfico do motor
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (166,361)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() #CRIAR UM GRÁFICO PARA ABRIR AO CLICAR
        
        #BOTÃO DE GRÁFICO DAS VARIÁVEIS
        Button: #Gráfico para encoder axial - RPM
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (192,489)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() 

        Button: #Gráfico para Torque axial - N.m
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (40,450)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('torque_axial') 

        Button: #Gráfico papit01 pressão do tubo azul - psi
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (385,270)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('pit01') 

        Button: #Gráfico tit01 temperaatura do tubo azul - ºC
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (370,305)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('tit01')  

        Button: #Gráfico pit02 pressão do tubo vermelho - psi
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (425,190)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('pit02') 

        Button: #Gráfico tit02 temperatura do tubo vermelho - ºC
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (405,57)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('tit02') 
            
        Button: #Gráfico pit03 pressão do tubo de ar - mmH20
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (475,489)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('pit03')  

        Button: #Gráfico Vazão no tubo de ar - N/m3
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (700,375)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('vazao')  

        Button: #Gráfico Velocidade no tubo de ar - m/s
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (700,290)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('velocidade')  

        Button: #Gráfico Temperatura no tubo de ar - ºC
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (700,212)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root.open_graph('temperatura') 



        #INFORMAÇÕES DO BOTÃO (i) DO MOTOR
        Button:
            text: "i" #Mostra as temperaturas referentes ao motor
            font_size: '14sp'
            bold: True
            size_hint: (None,None)
            size: ("16dp","16dp")
            background_normal: ""
            background_color: (0,0,0,0)
            color: (0.4,0.4,0.4,1)
            border: (16,16,16,16)
            pos: (165,435)
            canvas.before: 
                Color:
                    rgb: 0.4,0.4,0.4
                Line:
                    width: 0.6
                    circle: (self.center_x, self.center_y,self.width/2)
            on_release: root._monitoraTemperatura.open()


        #INFORMAÇÕES DO BOTÃO (i) DO COMPRESSOR
        Button:
            text: "i" #Mostra as tensões referentes ao compressor
            font_size: '14sp'
            bold: True
            size_hint: (None,None)
            size: ("16dp","16dp")
            background_normal: ""
            background_color: (0,0,0,0)
            color: (0.4,0.4,0.4,1)
            border: (16,16,16,16)
            pos: (186,102)
            canvas.before: 
                Color:
                    rgb: 0.4,0.4,0.4
                Line:
                    width: 0.6
                    circle: (self.center_x, self.center_y,self.width/2)
            on_release: root._monitoraCompressor.open()

        # Painel de botões à direita sobre a imagem
        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.2, 0.8)  # 20% da largura e 80% da altura
            pos_hint: {'right': 0.98, 'center_y': 0.47}  # Alinha à direita
            spacing: 4.5

            Button:
                text: "Dados Históricos"
                size_hint_y: None
                height: '50dp'
                background_color: (0.4,0.4,0.4,1)
                background_normal: ""
                color: (1,1,1,1)
                on_release: root._hgraph.open()

<TempLabel@Label>:
    font_size: 16
    bold: True
    halign: 'center'
    color: 0.4,0.4,0.4,1


