#:kivy 2.3.1

<MainWidget>: # Regra do kivy
    orientation: 'vertical' # Divide a tela em 2 caixas horizontais
    canvas: 
        Color: 
            rgb: 0.5,0.5,0.5 # Cinza
        Rectangle: # Desenha uma caixa retangular
            size: self.size
    BoxLayout:
        orientation: 'horizontal' # Cria um layout filho que vai ser divido em duas caixas veticais
        size_hint: (1,0.12)
        spacing: 10 
        Label:
            text: 'SCADA Refrigeração v1.0'
            size_hint_x: None
            width: 300
        BoxLayout:
            orientation:'vertical' # Vai "empilhar" coisas uma em cima da outra
            size_hint_x: None # Desabilita o dimensionamento horizontal
            width: 400
            Label:
                text: 'Configurações de conexão'
            BoxLayout:
                orientation:'horizontal'
                Button: 
                    text: "MODBUS"
                    on_release: root._modbusPopup.open()
                Button: 
                    text: "Scan Time"
                    on_release: root._scanPopup.open()
        Image:
            id: img_con
            size_hint_x: None
            width: 80
            source: 'assets/desconectado.png'
            pos_hint: {'top':1,'right':1}
### DAQUI PRA CIMA FOI FEITA A BARRA DE CIMA DO LAYOUT ###

### DAQUI PRA BAIXO FOI FEITA A BARRA DE BAIXO ###

    FloatLayout:
        canvas:
            Color:
                rgb: 1,1,1 # Fundo branco para não ter contraste em relação a imagem de fundo
            Rectangle: 
                size: self.size
        Image: 
            source: 'assets/fundo.png'

        Label: 
            id: lb_encoder_axial
            size_hint: (None,None)
            size: (15,15)
            canvas: 
                Color:
                    rgb:(0.165,0.376,0.647)
                Rectangle: 
                    size: self.size 
                    pos: (150,400)
        
        Label:
            id:  encoder_axial #Rotação mecânica do ventilador
            text: '-.- RPM'
            fint_size: 25
            bold: True
            halign: 'center'
            pos_hint: {'x':-0.326,'y':0.365}
            color: 0.4,0.4,0.4,1

        TempLabel:
            id:  torque_axial
            text: '-.- N.m'
            pos_hint: {'x':-0.457,'y':0.30}

        TempLabel:
            id:  pit01 #Pressão do tubo azul 
            text: '-.- psi'
            pos_hint: {'x':-0.045,'y':0.085}


        TempLabel:
            id:  pit02 #Pressão do tubo vermelho
            text: '-.- psi'
            pos_hint: {'x':-0.03,'y':-0.09}

        TempLabel:
            id:  pit03 #Pressão do ar de entrada
            text: '-.- mmH2O'
            pos_hint: {'x':-0.2,'y':0.44}

        TempLabel:
            id: tit01 #Temperatura do tubo azul
            text: '-.- °C'
            pos_hint: {'x':-0.045,'y':0.125}

        TempLabel:
            id: tit02 #Temperatura do tubo vermelho (trocador de calor)
            text: '-.- °C'
            pos_hint: {'x':-0.025,'y':-0.305}

        TempLabel:
            id: vazao #Vazão do ar na saída do tubo
            text: '-.- m³/h'
            pos_hint: {'x':0.44,'y':0.41}

        TempLabel:
            id: velocidade #Velocidade do ar na saída do tubo
            text: '-.- m/s'
            pos_hint: {'x':0.438,'y':0.37}

        TempLabel:
            id: temperatura #temperatura do ar na saída do tubo
            text: '-.- °C'
            pos_hint: {'x':0.438,'y':0.33}
        Button:
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open()

        #ACIONAMENTO DO COMPRESSOR 1 (DECIDIR QUAL)
        Button: 
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (50,20)
            background_normal: 'assets/acionamento.png'
            background_down: 'assets/acionamento.png'
            on_release:
                root._graph.open() #CRIAR UM LAYOUT PARA ABRIR QUANDO CLICAR
        Button: #Gráfico do compressor 1 (DECIDIR QUAL)
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (78,20)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() #CRIAR UM GRÁFICO PARA ABRIR AO CLICAR

        #ACIONAMENTO DO COMPRESSOR 2 (DECIDIR QUAL)
        Button: 
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (230,20)
            background_normal: 'assets/acionamento.png'
            background_down: 'assets/acionamento.png'
            on_release:
                root._graph.open() #CRIAR UM LAYOUT PARA ABRIR QUANDO CLICAR
        Button: #Gráfico do compressor 2(DECIDIR QUAL)
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (258,20)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() #CRIAR UM GRÁFICO PARA ABRIR AO CLICAR

        #ACIONAMENTO O MOTOR
        Button: 
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (107,361)
            background_normal: 'assets/acionamento.png'
            background_down: 'assets/acionamento.png'
            on_release:
                root._graph.open() #CRIAR UM LAYOUT PARA ABRIR QUANDO CLICAR
        Button: #Gráfico do motor
            size_hint: (None, None)
            size: (0.65*90, 0.65*90)
            pos: (137,361)
            background_normal: 'assets/graph.png'
            background_down: 'assets/graph.png'
            on_release:
                root._graph.open() #CRIAR UM GRÁFICO PARA ABRIR AO CLICAR


        #INFORMAÇÕES DO BOTÃO (i) DO MOTOR
        Button:
            text: "i" #Mostra as temperaturas referentes ao motor
            font_size: '14sp'
            bold: True
            size_hint: (None,None)
            size: ("16dp","16dp")
            background_normal: ""
            background_color: (0,0,0,0)
            color: (0.4,0.4,0.4,1)
            border: (16,16,16,16)
            pos: (155,440)
            canvas.before: 
                Color:
                    rgb: 0.4,0.4,0.4
                Line:
                    width: 0.6
                    circle: (self.center_x, self.center_y,self.width/2)
            on_release: root._monitoraTemperatura.open()


        #INFORMAÇÕES DO BOTÃO (i) DO COMPRESSOR
        Button:
            text: "i" #Mostra as tensões referentes ao compressor
            font_size: '14sp'
            bold: True
            size_hint: (None,None)
            size: ("16dp","16dp")
            background_normal: ""
            background_color: (0,0,0,0)
            color: (0.4,0.4,0.4,1)
            border: (16,16,16,16)
            pos: (174,115)
            canvas.before: 
                Color:
                    rgb: 0.4,0.4,0.4
                Line:
                    width: 0.6
                    circle: (self.center_x, self.center_y,self.width/2)
            on_release: root._monitoraCompressor.open()

        # Painel de botões à direita sobre a imagem
        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.2, 0.8)  # 20% da largura e 80% da altura
            pos_hint: {'right': 0.98, 'center_y': 0.47}  # Alinha à direita
            spacing: 4.5

            #Button:
            #    text: "Comandos"
            #    size_hint_y: None
            #    height: '50dp'
            #    background_color: (0.4,0.4,0.4,1)
            #    background_normal: ""
            #    color: (1,1,1,1)
            #    on_release: 

            Button:
                text: "Dados Históricos"
                size_hint_y: None
                height: '50dp'
                background_color: (0.4,0.4,0.4,1)
                background_normal: ""
                color: (1,1,1,1)
                on_release: root._hgraph.open()

<TempLabel@Label>:
    font_size: 16
    bold: True
    halign: 'center'
    color: 0.4,0.4,0.4,1

<DinamicBar>:
    orientation: "horizontal"
    spacing: 10

    Label:
        text: "TESTE BARRA"
        size_hint: None, None
        size: 80, 30

    ProgressBar:
        min: 0
        max: 60
        value: root.encoder_axial
        size_hint: 1, None
        height: 30

    Label:
        text: f"{root.encoder_axial:.1f} °C"
        size_hint: None, None
        size: 60, 30