#:kivy 2.3.1

<ModbusPopup>:
    title: "Configurações MODBUS"
    size_hint_y: None
    size_hint_x: 0.4
    height: 250  # Aumentando altura total do Popup
    
    BoxLayout:
        orientation: 'vertical'
        id: layout
        spacing: 10  # Espaçamento entre os elementos
        padding: [10, 10, 10, 10]

        GridLayout:
            cols: 2
            size_hint_y: None
            height: self.minimum_height
            row_default_height: 40  # Definindo altura fixa das linhas
            row_force_default: True  # Forçando todas as linhas a terem a mesma altura

            Label:
                text: "IP"
                font_size: 14
            TextInput:
                id: txt_ip
                text: "127.0.0.1"
                font_size: 14
                halign: 'center'
                valign: 'middle'
                size_hint_y: None
                height: 35  # Ajuste na altura do campo

            Label:
                text: "Porta"
                font_size: 14
            TextInput:
                id: txt_porta
                text: "502"
                font_size: 14
                halign: 'center'
                valign: 'middle'
                size_hint_y: None
                height: 35

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 50  # Aumentando a área dos botões
            spacing: 10
            Button:
                text: "Conectar"
                on_release:
                    root.clearInfo()
                    app.root.startDataRead(txt_ip.text, int(txt_porta.text))
            Button:
                text: "Fechar"
                on_release: 
                    root.dismiss()
                    root.clearInfo()


<ScanPopup>:
    title: "Configurações ScanTime"
    size_hint_y: None
    size_hint_x: 0.4
    height: 180  # Aumentando um pouco a altura
    
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: [10, 10, 10, 10]

        GridLayout:
            cols: 2
            size_hint_y: None
            height: self.minimum_height
            row_default_height: 40
            row_force_default: True

            Label:
                text: "ScanTime [ms]"
                font_size: 14
            TextInput:
                id: txt_st
                text: "502"
                font_size: 14
                halign: 'center'
                valign: 'middle'
                size_hint_y: None
                height: 35

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 50
            spacing: 10
            Button:
                text: "Configurar"
                on_release:
                    app.root._scan_time = int(txt_st.text)
                    root.dismiss()
            Button:
                text: "Fechar"
                on_release: root.dismiss()

<MonitoramentoPopup>:
    size_hint_y: None
    size_hint_x: 0.6
    height: 300

<MonitoraTemperatura@MonitoramentoPopup>:
    title: 'Temperaturas'
    GridLayout:
        cols:2
        rows:4
        Label:
            text: "Carcaça"
        Label:
            id: temp_carc
            text: '-.- °C'
        Label:
            text: "Enrolamento Fase R"
        Label:
            id: temp_r
            text: '-.- °C'
        Label:
            text: "Enrolamento Fase S"
        Label:
            id: temp_s
            text: '-.- °C'
        Label:
            text: "Enrolamento Fase T"
        Label:
            id: temp_t
            text: '-.- °C'


<MonitoraCompressor@MonitoramentoPopup>:
    title: 'Medições Elétricas'
    title_align: 'center'
    size_hint_x: 0.9  # Janela maior para melhor visualização
    size_hint_y: 0.9  # Janela maior para melhor visualização
    GridLayout:
        cols: 1  # Seções separadas para tensões/correntes e potências

        # Seção de Potências
        GridLayout:
            cols: 4  # Agora são 4 colunas: Medição, Potência Ativa, Potência Reativa, Potência Aparente
            rows: 4  # Ajustado para as fases e total

            Label:
                text: "Medição"
                bold: True
            Label:
                text: "Potência Ativa"
                bold: True
            Label:
                text: "Potência Reativa"
                bold: True
            Label:
                text: "Potência Aparente"
                bold: True

            # Potências - Fase R
            Label:
                text: "Fase R"
            Label:
                id: ativa_r_co
                text: '-.- W'
            Label:
                id: reativa_r_co
                text: '-.- VAr'
            Label:
                id: aparente_r_co
                text: '-.- VA'

            # Potências - Fase S
            Label:
                text: "Fase S"
            Label:
                id: ativa_s_co
                text: '-.- W'
            Label:
                id: reativa_s_co
                text: '-.- VAr'
            Label:
                id: aparente_s_co
                text: '-.- VA'

            # Potências - Fase T
            Label:
                text: "Fase T"
            Label:
                id: ativa_t_co
                text: '-.- W'
            Label:
                id: reativa_t_co
                text: '-.- VAr'
            Label:
                id: aparente_t_co
                text: '-.- VA'

            # Potências - Total
            Label:
                text: "Total"
            Label:
                id: ativa_total_co
                text: '-.- W'
            Label:
                id: reativa_total_co
                text: '-.- VAr'
            Label:
                id: aparente_total_co
                text: '-.- VA'

        # Seção de Tensões e Correntes
        GridLayout:
            cols: 3  # Apenas 3 colunas: Medição, Valor, Unidade
            rows: 9  # Ajuste conforme necessário

            Label:
                text: "Medição"
                bold: True
            Label:
                text: "Valor"
                bold: True
            Label:
                text: "Unidade"
                bold: True

            # Tensões
            Label:
                text: "Fase RS"
            Label:
                id: tensao_rs_co
                text: '-.-'
            Label:
                text: "V"

            Label:
                text: "Fase ST"
            Label:
                id: tensao_st_co
                text: '-.-'
            Label:
                text: "V"

            Label:
                text: "Fase TR"
            Label:
                id: tensao_tr_co
                text: '-.-'
            Label:
                text: "V"

            # Correntes
            Label:
                text: "Corrente R"
            Label:
                id: corrente_r_co
                text: '-.-'
            Label:
                text: "A"

            Label:
                text: "Corrente S"
            Label:
                id: corrente_s_co
                text: '-.-'
            Label:
                text: "A"

            Label:
                text: "Corrente T"
            Label:
                id: corrente_t_co
                text: '-.-'
            Label:
                text: "A"

            Label:
                text: "Corrente N"
            Label:
                id: corrente_n_co
                text: '-.-'
            Label:
                text: "A"

            Label:
                text: "Média"
            Label:
                id: corrente_media_co
                text: '-.-'
            Label:
                text: "A"

<DataGraphPopup>:
    title: "Gráfico de temperatura no ventilador"
    BoxLayout:
        orientation: 'vertical'
        TimeSeriesGraph:
            id: graph
            xlabel: 'Horário'  # Rótulo do eixo X
            ylabel: 'Valor'  # Rótulo do eixo Y
            background_color: 0.3, 0.3, 0.3, 1  # Fundo cinza escuro
            x_ticks_minor: 1  # Pequenos marcadores no eixo X
            x_ticks_major: 5  # Grandes marcadores no eixo X
            y_ticks_major: 10  # Grandes marcadores no eixo Y
            y_grid_label: True  # Ativar rótulos no eixo Y
            x_grid_label: True  # Ativar rótulos no eixo X
            padding: 10  # Aumentar espaçamento para os rótulos aparecerem
            x_grid: True
            y_grid: True
            xmin: 0
            ymin: 0
            ymax: 100  # Inicialmente, ajustado dinamicamente depois
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.05)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: (0.5,1)
                Label:
                    size_hint: (0.3,1)
                    text: "Número do pontos do gráfico"
                LabeledCheckBoxDataGraph:
                    id: mp20
                    on_kv_post:
                        self.ids.label.text = '20'
                        self.ids.checkbox.group = 'cb_group'
                        self.ids.checkbox.active = True
                LabeledCheckBoxDataGraph:
                    id: mp50
                    on_kv_post:
                        self.ids.label.text = '50'
                        self.ids.checkbox.group = 'cb_group'
                LabeledCheckBoxDataGraph:
                    id: mp100
                    on_kv_post:
                        self.ids.label.text = '100'
                        self.ids.checkbox.group = 'cb_group'
            Button:
                text: "Fechar"
                size_hint: (0.2,1)
                on_release: root.dismiss()


<LabeledCheckBoxDataGraph>:
    orientation: 'horizontal'
    size_hint: (0.1, 1)
    CheckBox:
        id: checkbox
        on_active: app.root._graph.ids.graph.setMaxPoints(int(label.text), 0) if app.root is not None else None
    Label:
        id: label


<HistGraphPopup>:
    title: "Histórico de Temperatura na Refinaria"
    BoxLayout:
        orientation: 'vertical'
        TimeSeriesGraph:
            id: graph
            xlabel: 'Horário'  # Rótulo do eixo X
            ylabel: 'Valor'  # Rótulo do eixo Y
            background_color: 0.3, 0.3, 0.3, 1  # Fundo cinza escuro
            x_ticks_minor: 1  # Pequenos marcadores no eixo X
            x_ticks_major: 5  # Grandes marcadores no eixo X
            y_ticks_major: 10  # Grandes marcadores no eixo Y
            y_grid_label: True  # Ativar rótulos no eixo Y
            x_grid_label: True  # Ativar rótulos no eixo X
            padding: 10  # Aumentar espaçamento para os rótulos aparecerem
            x_grid: True
            y_grid: True
            xmin: 0
            ymin: 0
            ymax: 100  # Inicialmente, ajustado dinamicamente depois
        ScrollView:
            size_hint: (1, 0.3)  # Ajusta a altura para rolagem caso tenha muitos sensores
            GridLayout:
                id: sensores
                cols: 3  # Exibe os sensores em múltiplas colunas para melhor organização
                size_hint_y: None
                height: self.minimum_height  # Ajusta a altura dinamicamente
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.08)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: (0.5,1)
                Label:
                    text: "Timestamp Inicial \r\n [size=12] (DD/MM/AAAA HH:MM:SS)[/size]"
                    size_hint: (1, 0.8)
                    halign: 'center'
                    markup: True
                TextInput:
                    id: txt_init_time
                    size_hint: (1, 1)
                    halign: 'center'
                    valign: 'middle'
                    multiline: False
                Label:
                    text: "Timestamp Final \r\n [size=12] (DD/MM/AAAA HH:MM:SS)[/size]"
                    halign: 'center'
                    size_hint: (1, 0.8)
                    markup: True
                TextInput:
                    id: txt_final_time
                    size_hint: (1, 1)
                    halign: 'center'
                    valign: 'middle'
                    multiline: False
                Button:
                    text: "Fechar"
                    size_hint: (0.2,1)
                    on_release: root.dismiss()


<LabeledCheckBoxHistGraph>:
    orientation: 'horizontal'
    size_hint: (1, None)
    height: 40
    CheckBox:
        id: checkbox
        on_active: app.root.getDataDB()
        size_hint_x: 0.2
    Label:
        id: label
        size_hint_x: 0.8
        text_size: self.size
        valign: 'center'


#TENTATIVA DO BOTÃO DE COMANDO - MOTOR (DEU CERTO!)
<ComandoPopup>:
    title:"COMANDOS DO MOTOR"
    title_align: 'center'
    bold: True
    font_size: 18
    size_hint_y: None
    size_hint_x: None
    height: 600
    width: 800
    auto_dismiss: False
    BoxLayout:
        id: comando_layout
        orientation:'vertical'
        size_hint_y: 0.9
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation:'vertical'
                padding: [20, 20, 20, 20]
                spacing: 10
                Label:
                    text: "VETILADOR"
                    bold: True
                    font_size: 18
                #BOTÃO PARA LIGAR O MOTOR            
                Button:
                    text: "Liga"
                    on_release: app.root.acionaMotor(1)

                #BOTÃO PARA DESLIGAR O MOTOR 
                Button:
                    text: "Desliga"
                    on_release: app.root.acionaMotor(2) 
                
                #BOTÃO RESET
                Button:
                    text: "Reset"
                    on_release: app.root.acionaMotor(3)


            BoxLayout:
            #BOTÕES PARA O TIPO DE PARTIDA
                orientation:'vertical'
                padding: [20, 20, 20, 20]
                spacing: 10
                Label:
                    text: "TIPO DE PARTIDA"
                    font_size: 18
                    bold: True

                #Partida DIRETA   
                Button:
                    text: "Direta"
                    on_release: app.root.tipoPartida("DIRETA")

                #Partida por Inversor 
                Button:
                    text: "Inversor"
                    on_release: app.root.tipoPartida("INVERSOR") 
                
                #Partida por Soft-Start
                Button:
                    text: "Soft-Start"
                    on_release: app.root.tipoPartida("SOFT-START")

            BoxLayout:
            #Manipulador de FREQUENCIA
                orientation:'vertical'
                Label:                      
                    text: 'FREQUÊNCIA [Hz]'
                    bold: True
                    font_size: 18

                Slider:
                    id: velocidade_inversor
                    min: 0
                    max: 61 
                    value_track: True
                    value_track_color: [1, 0, 0, 1]
                    on_touch_up: 
                        app.root.writeHoldingRegister(1313, int(velocidade_inversor.value)*10)
                Label:
                    text: str(int(velocidade_inversor.value))

                Label:                      
                    text: 'TEMPO DA RAMPA [s]'
                    bold: True
                    font_size: 18
                Slider:
                    id: tempo_rampa
                    min: 0
                    max: 101
                    value_track: True
                    value_track_color: [1, 0, 0, 1]
                    on_touch_move: 
                        app.root.setRampa(tempo_rampa.value)
                Label:
                    text: str(int(tempo_rampa.value))

        BoxLayout:
            orientation: 'vertical'
            padding: [20, 20, 20, 20]
            spacing: 10

            Label:
            #ESCOLHE O TIPO DE VENTILADOR
                text: "SELEÇÃO DO VENTILADOR"
                font_size: 18
                bold: True

            BoxLayout:
                orientation: 'horizontal'
                spacing: 10
                #VENTILADOR AXIAL
                ToggleButton:
                    text: "Axial"
                    group: "ventilador"
                #VENTILADOR RADIAL
                ToggleButton:
                    text: "Radial"
                    group: "ventilador"

            Label:
            #ESCOLHE O MODO DE DESEMPENHO DO MOTOR
                text: "SELEÇÃO DO MOTOR"
                font_size: 18
                bold: True

            BoxLayout:
                orientation: 'horizontal'
                spacing: 10
                #Alto Rendimento
                ToggleButton:
                    text: "Alto Rendimento"
                    group: "motor"
                #Convencional
                ToggleButton:
                    text: "Convencional"
                    group: "motor"

            #Botões para confirmar e cancelar        
            BoxLayout:
                orientation: 'horizontal'
                spacing: 10
                Button:
                    text: "Cancelar"
                    size_hint_y: None
                    height: 35
                    on_release: root.dismiss()





<ComandoCOPopup>:
    title:"COMANDOS DO COMPRESSOR"
    title_align: 'center'
    bold: True
    font_size: 18
    size_hint_y: None
    size_hint_x: None
    height: 600
    width: 800
    auto_dismiss: False
    BoxLayout:
        id: comando_layout
        orientation:'horizontal'
        size_hint_y: 0.9
        BoxLayout:
            orientation: 'vertical'
            BoxLayout:
                orientation:'vertical'
                padding: [20, 20, 20, 20]
                spacing: 10
                Label:
                    text: "SELEÇÃO DO COMPRESSOR"
                    font_size: 18
                    bold: True
                ToggleButton:
                    text: "SCROOL"
                    group: "compressor"
                ToggleButton:
                    text: "HERMÉTICO"
                    group: "compressor"
            BoxLayout:
                orientation:'vertical'
                padding: [20, 20, 20, 20]
                spacing: 10
                Label:
                    text: "SELEÇÃO DO COMPRESSOR"
                    font_size: 18
                    bold: True
                Button:
                    text: "Liga"
                    group: "compressor"
                Button:
                    text: "Desliga"
                    group: "compressor"

        BoxLayout:
            orientation: 'vertical'
            padding: [20, 20, 20, 20]       
            spacing: 10
            Label:
                text: "UMIDIFICADOR"
                font_size: 18
                bold: True
            Button:
                text: "Liga"
                group: "compressor"
            Button:
                text: "Desliga"
                group: "compressor"
            BoxLayout:
                orientation: 'horizontal'
                padding: [20, 20, 20, 20]       
                spacing: 10
                Button:
                    text: "MAN SEL."
                Button:
                    text: "AUTO SEL."
                Button:
                    text: "MANUAL"
            Label:
                text: "FREQUÊNCIA [Hz]"
                font_size: 18
                bold: True
            Slider:
                id: velocidade_inversor #AJUSTAR
                min: 0
                max: 61 
                value_track: True
                value_track_color: [1, 0, 0, 1]
                on_touch_move: 

            Label:
                text: str(int(velocidade_inversor.value))
        BoxLayout:
            orientation: 'vertical'
            padding: [20, 20, 20, 20]       
            spacing: 10
            Label:
                text: "AQUECEDOR 1"
                font_size: 18
                bold: True
            Button:
                text: "Liga"
                group: "aquecedor"
            Button:
                text: "Desliga"
                group: "aquecedor"
            BoxLayout:
                orientation: 'horizontal'
                padding: [20, 20, 20, 20]       
                spacing: 10
        
            Label:
                text: "AQUECEDOR 2"
                font_size: 18
                bold: True
            Button:
                text: "Liga"
                group: "aquecedor"
            Button:
                text: "Desliga"
                group: "aquecedor"
            BoxLayout:
                orientation: 'horizontal'
                padding: [20, 20, 20, 20]       
                spacing: 10
                
            #Botões para confirmar e cancelar        
            BoxLayout:
                orientation: 'horizontal'
                spacing: 10
                Button:
                    text: "Cancelar"
                    size_hint_y: None
                    height: 35
                    on_release: root.dismiss()








            
                
